CREATE TABLE ORIGEM (
  ID    INT(9)       NOT NULL AUTO_INCREMENT,
  ALIAS VARCHAR(50)  NOT NULL,
  NOME  VARCHAR(100) NOT NULL,
  CONSTRAINT PK_ORIGEM PRIMARY KEY (ID)
);
ALTER TABLE ORIGEM ADD CONSTRAINT UQ_ORIGEM_ALIAS UNIQUE (ALIAS);
ALTER TABLE ORIGEM ADD CONSTRAINT UQ_ORIGEM_NOME UNIQUE (NOME);

CREATE TABLE EXTRATO (
  ID              INT(9)        NOT NULL AUTO_INCREMENT,
  DESCRICAO       VARCHAR(255)  NOT NULL,
  DATA_REFERENCIA DATE          NOT NULL,
  METADADOS       LONGTEXT      NOT NULL,
  SALDO_INICIAL   DECIMAL(9, 2) NOT NULL,
  ORIGEM          INT(9)        NOT NULL,
  CONSTRAINT PK_EXTRATO PRIMARY KEY (ID)
);
ALTER TABLE EXTRATO ADD CONSTRAINT FK_EXTRATO_ORIGEM FOREIGN KEY (ORIGEM) REFERENCES ORIGEM (ID);

CREATE TABLE MOVIMENTACAO (
  ID              INT(9)        NOT NULL AUTO_INCREMENT,
  DATA            DATE          NOT NULL,
  NUMERODOCUMENTO VARCHAR(50)   NULL,
  DESCRICAO       VARCHAR(255)  NOT NULL,
  DESCRICAO2      VARCHAR(255)  NULL,
  VALOR           DECIMAL(9, 2) NOT NULL,
  EXTRATO         INT(9)        NOT NULL,
  CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (ID)
);
ALTER TABLE MOVIMENTACAO ADD CONSTRAINT FK_MOVIMENTACAO_EXTRATO FOREIGN KEY (EXTRATO) REFERENCES EXTRATO (ID);