# Sample variable
aa:
  bb:
    cc: Your Java's home is ${JAVA_HOME}

spring:

  # DATASOURCE/JPA Configuration
  datasource:
    url: jdbc:mysql://${OPENSHIFT_MYSQL_DB_HOST}:${OPENSHIFT_MYSQL_DB_PORT}/${OPENSHIFT_GEAR_NAME}
    username: ${OPENSHIFT_MYSQL_DB_USERNAME}
    password: ${OPENSHIFT_MYSQL_DB_PASSWORD}
    # Keep the connection alive if idle for a long time (needed in production)
    #testWhileIdle: true
    #validationQuery: SELECT 1

  jpa:
    show-sql: true
    # spring.jpa.properties.* for Hibernate native properties (the prefix is stripped before adding to the EntityMgr)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

        # Disable warning "Attempted to specify unsupported NamingStrategy via setting (...)"
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        ejb.naming_strategy_delegator: