# Sample variable
aa:
  bb:
    cc: Your Java's home is ${JAVA_HOME}
application:
  message: Hello, Bob

spring:

  velocity:
    dateToolAttribute: dateTool
    #resourceLoaderPath: classpath:/

  # DATASOURCE/JPA Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_H}:3306/prp
    username: ${MYSQL_U}
    password: ${MYSQL_P}
    # Keep the connection alive if idle for a long time (needed in production)
    #testWhileIdle: true
    #validationQuery: SELECT 1

  jpa:
    show-sql: false
    # spring.jpa.properties.* for Hibernate native properties (the prefix is stripped before adding to the EntityMgr)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect